### ISSUE TITLE
Unable to install on Arch with 6.8.9 kernel

### ISSUE THREAD

**Issue by celtichawk** [KanuX-14/GeneriKit#6]
Just tried to install this module again on my Arch box and running into the following with kernel 6.8.9

I get this directly after typing make hid-sony modules&&sudo make install clean in the directory

Added hid-sony to the recipe.
mkdir: created directory '/home/jace/games/generikit-hid-sony/build'
'drivers/hid/generikit-hid-sony.c' -> '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.c'
'drivers/hid/generikit-hid-ids.h' -> '/home/jace/games/generikit-hid-sony/build/generikit-hid-ids.h'
make[1]: Entering directory '/usr/lib/modules/6.8.9-arch1-2/build'
  CC [M]  /home/jace/games/generikit-hid-sony/build/generikit-hid-sony.o
  MODPOST /home/jace/games/generikit-hid-sony/build/Module.symvers
  CC [M]  /home/jace/games/generikit-hid-sony/build/generikit-hid-sony.mod.o
  LD [M]  /home/jace/games/generikit-hid-sony/build/generikit-hid-sony.ko
  BTF [M] /home/jace/games/generikit-hid-sony/build/generikit-hid-sony.ko
make[1]: Leaving directory '/usr/lib/modules/6.8.9-arch1-2/build'
[sudo] password for jace: 
rmmod: ERROR: Module hid_sony is not currently loaded
blacklist hid-sony
make[1]: Entering directory '/usr/lib/modules/6.8.9-arch1-2/build'
  INSTALL /lib/modules/6.8.9-arch1-2/updates/generikit-hid-sony.ko
  SIGN    /lib/modules/6.8.9-arch1-2/updates/generikit-hid-sony.ko
At main.c:167:
- SSL error:FFFFFFFF80000002:system library::No such file or directory: crypto/bio/bss_file.c:67
- SSL error:10000080:BIO routines::no such file: crypto/bio/bss_file.c:75
sign-file: ./certs/signing_key.pem
  ZSTD    /lib/modules/6.8.9-arch1-2/updates/generikit-hid-sony.ko.zst
  DEPMOD  /lib/modules/6.8.9-arch1-2
make[1]: Leaving directory '/usr/lib/modules/6.8.9-arch1-2/build'
insmod /lib/modules/6.8.9-arch1-2/updates/generikit-hid-sony.ko.zst 
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.mod.o'
removed '/home/jace/games/generikit-hid-sony/build/new_modules'
removed '/home/jace/games/generikit-hid-sony/build/Makefile'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-ids.h'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.c'
removed '/home/jace/games/generikit-hid-sony/build/.generikit-hid-sony.mod.o.cmd'
removed '/home/jace/games/generikit-hid-sony/build/.modules.order.cmd'
removed '/home/jace/games/generikit-hid-sony/build/.generikit-hid-sony.ko.cmd'
removed '/home/jace/games/generikit-hid-sony/build/modules.order'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.mod'
removed '/home/jace/games/generikit-hid-sony/build/old_modules'
removed '/home/jace/games/generikit-hid-sony/build/.generikit-hid-sony.o.cmd'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.mod.c'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.o'
removed '/home/jace/games/generikit-hid-sony/build/Module.symvers'
removed '/home/jace/games/generikit-hid-sony/build/.Module.symvers.cmd'
removed '/home/jace/games/generikit-hid-sony/build/.generikit-hid-sony.mod.cmd'
removed '/home/jace/games/generikit-hid-sony/build/generikit-hid-sony.ko'
removed directory '/home/jace/games/generikit-hid-sony/build'
jace@linuxmint:~/games/generikit-hid-sony$ 
jace@linuxmint:~/games/generikit-hid-sony$ 

The dmesg indicates there is a -71 error with the USB controller, it was working fine before a kernel update however, the dmesg  output is as follows:

[  272.235772] usb 1-7: New USB device found, idVendor=054c, idProduct=0268, bcdDevice= 0.01
[  272.235786] usb 1-7: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  272.235794] usb 1-7: Product: PS3 Controller
[  272.240686] usbhid 1-7:1.0: can't add hid device: -71
[  272.304076] usbhid: probe of 1-7:1.0 failed with error -71
[  272.304319] usb 1-7: USB disconnect, device number 6

**Comment by SimplyCEO** [comment]
Weird. The patch is intended to disconnect and reconnect the device (because of my lack of debugging). Mine shows:
```
[  +4.128278] usb 1-2.1: new full-speed USB device number 47 using xhci_hcd
[  +0.200534] usb 1-2.1: New USB device found, idVendor=054c, idProduct=0268, bcdDevice= 0.01
[  +0.000005] usb 1-2.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  +0.000002] usb 1-2.1: Product: PS3 Controller
[  +0.006247] usbhid 1-2.1:1.0: can't add hid device: -32
[  +0.000074] usbhid: probe of 1-2.1:1.0 failed with error -32
[  +0.016749] usb 1-2.1: USB disconnect, device number 47
[  +0.544393] usb 1-2.1: new full-speed USB device number 48 using xhci_hcd
[  +0.203646] usb 1-2.1: New USB device found, idVendor=054c, idProduct=0268, bcdDevice= 5.72
[  +0.000005] usb 1-2.1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[  +0.000001] usb 1-2.1: Product: PS3 Controller
[  +0.007543] input: PS3 Controller Motion Sensors as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:054C:0268.0018/input/input47
[  +0.052464] input: PS3 Controller as /devices/pci0000:00/0000:00:14.0/usb1/1-2/1-2.1/1-2.1:1.0/0003:054C:0268.0018/input/input46
[  +0.000161] sony 0003:054C:0268.0018: input,hiddev98,hidraw4: USB HID v81.11 Joystick [PS3 Controller] on usb-0000:00:14.0-2.1/input0
```

Is your dmesg outputting `xhci_hcd` connection? I know xHCI is meant to run USB 3.x, but I connect to my USB 2 port and it still works.<br>
Do you think it could be a USB malfunction?

**Comment by celtichawk** [comment]
I'm not sure. The master branch is the one giving the above errors about missing certs however and it looks like the module fails to install due to that however as per the first bit up there however, I'm guessing at a missing cert since that is what googling it has given me for a quick result.
[ 2240.331840] generikit_hid_sony: loading out-of-tree module taints kernel.
[ 2240.331846] generikit_hid_sony: module verification failed: signature and/or required key missing - tainting kernel
[ 2240.333344] generikit_hid_sony: unknown parameter 'generikit-hid-sony' ignored

**Comment by SimplyCEO** [comment]
From what I've read, taints can be ignored. They become a problem when the device has Secure Boot enabled it seems.

Right now I'm checking the [mainstream usbhid](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hid/usbhid/hid-core.c#n1342) function that prints the error.

I don't know what is causing the errors. It may need a lot of time to debug the kernel.

**Comment by celtichawk** [comment]
I'm going back over the log and this leaps out at me:

SIGN /lib/modules/6.8.9-arch1-2/updates/generikit-hid-sony.ko
At main.c:167:

    SSL error:FFFFFFFF80000002:system library::No such file or directory: crypto/bio/bss_file.c:67
    SSL error:10000080:BIO routines::no such file: crypto/bio/bss_file.c:75
    sign-file: ./certs/signing_key.pem

A look at dmesg says it failed to install so it is ignoring the module though then it goes on about taints which I am starting to think is not the cause. I'm not sure why it is failing to sign the module, this just started happening with the latest Arch kernel update for me

**Comment by celtichawk** [comment]
Solved this with dkms on Arch which for some reason I didn't have, so I'll close this and put it in my notes to use the devel branch

**Comment by SimplyCEO** [comment]
That was incredibly weird then, because for me it just don't work when `hid-sony` and `generikit-hid-sony` is loaded together.

Good to know it is working.
